"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Activity, Boxes, FileText, FolderKanban, MessageSquareQuote, ReceiptText, Star, UsersRound } from "lucide-react";
import { AdminGuard } from "@/components/guard";
import { AdminShell, Head } from "@/components/shell";
import { requireSupabase } from "@/lib/supabase";
import { fcfa } from "@/lib/format";

type Order = { total_fcfa: number; status: string; payment_status: string; created_at: string };
type Review = { id: string; rating: number; comment: string; created_at: string; status: string; user_id: string | null };
type Audit = { id: number; action: string; entity_type: string; entity_id: string | null; details: Record<string, unknown>; actor_id: string | null; created_at: string; actorName?: string };
type Counts = { admins: number; customers: number; products: number; categories: number; articles: number; orders: number };
const actionNames: Record<string, string> = { CMS_INSERT: "a ajouté", CMS_UPDATE: "a modifié", CMS_DELETE: "a supprimé", ORDER_STATUS_CHANGED: "a changé le statut d’une commande", PAYMENT_STATUS_CHANGED: "a mis à jour le paiement", USER_ROLE_CHANGED: "a modifié un accès", STAFF_INVITED: "a invité un membre d’équipe", STAFF_REMOVED: "a retiré un membre d’équipe" };
const entityNames: Record<string, string> = { product: "le produit", category: "la catégorie", article: "l’article", section: "la section", site_setting: "le contenu du site", profile: "un compte", order: "une commande", review: "un avis" };
export default function Overview() {
 const [counts,setCounts]=useState<Counts>({admins:0,customers:0,products:0,categories:0,articles:0,orders:0});const [orders,setOrders]=useState<Order[]>([]);const [reviews,setReviews]=useState<Review[]>([]);const [audit,setAudit]=useState<Audit[]>([]);const [error,setError]=useState("");
 useEffect(()=>{void(async()=>{const s=requireSupabase();const [admins,customers,products,categories,articles,orderRows,reviewRows,logs]=await Promise.all([s.from("profiles").select("id",{count:"exact",head:true}).in("role",["system_admin","store_manager"]).eq("active",true),s.from("profiles").select("id",{count:"exact",head:true}).eq("role","customer"),s.from("products").select("id",{count:"exact",head:true}),s.from("categories").select("id",{count:"exact",head:true}),s.from("site_articles").select("id",{count:"exact",head:true}),s.from("orders").select("total_fcfa,status,payment_status,created_at").order("created_at",{ascending:false}),s.from("site_reviews").select("id,rating,comment,created_at,status,user_id").neq("status","hidden").order("created_at",{ascending:false}),s.from("audit_logs").select("id,action,entity_type,entity_id,details,actor_id,created_at").order("created_at",{ascending:false}).limit(12)]);const failures=[admins,customers,products,categories,articles,orderRows,reviewRows,logs].filter(r=>r.error);if(failures.length)setError("Certaines informations ne sont pas disponibles pour le moment. Réessayez plus tard.");const orderData=(orderRows.data||[]) as Order[];setCounts({admins:admins.count||0,customers:customers.count||0,products:products.count||0,categories:categories.count||0,articles:articles.count||0,orders:orderData.length});setOrders(orderData);setReviews((reviewRows.data||[]) as Review[]);const raw=(logs.data||[]) as Audit[];const ids=Array.from(new Set(raw.map(row=>row.actor_id).filter((id):id is string=>Boolean(id))));const people=ids.length?await s.from("profiles").select("id,full_name,email").in("id",ids):{data:[]};const names=new Map((people.data||[]).map(person=>[person.id,person.full_name||person.email||"Administrateur"]));setAudit(raw.map(row=>({...row,actorName:row.actor_id?names.get(row.actor_id)||"Administrateur":"Système"})));})()},[]);
 const summary=useMemo(()=>{const settled=new Set(["CONFIRMED","PREPARING","OUT_FOR_DELIVERY","DELIVERED"]);const buckets=Array.from({length:6},(_,i)=>{const date=new Date();date.setDate(1);date.setMonth(date.getMonth()-(5-i));return {key:`${date.getFullYear()}-${date.getMonth()}`,label:date.toLocaleDateString("fr-FR",{month:"short"}),amount:0};});for(const order of orders){const amount=Number(order.total_fcfa)||0;const date=new Date(order.created_at);const item=buckets.find(b=>b.key===`${date.getFullYear()}-${date.getMonth()}`);if(item&&order.payment_status==="PAID")item.amount+=amount;}return {pending:orders.filter(o=>o.status==="PENDING").length,confirmed:orders.filter(o=>o.status==="CONFIRMED").length,delivered:orders.filter(o=>o.status==="DELIVERED").length,cancelled:orders.filter(o=>o.status==="CANCELLED").length,generated:orders.filter(o=>settled.has(o.status)).reduce((sum,o)=>sum+Number(o.total_fcfa||0),0),paid:orders.filter(o=>o.payment_status==="PAID").reduce((sum,o)=>sum+Number(o.total_fcfa||0),0),buckets};},[orders]);
 const eligible=reviews.filter(r=>r.status!=="hidden");const average=eligible.length?eligible.reduce((sum,r)=>sum+r.rating,0)/eligible.length:0;const maxMonth=Math.max(...summary.buckets.map(b=>b.amount),1);
 const cards=[{label:"Équipe",value:counts.admins,icon:UsersRound,href:"/users"},{label:"Clients inscrits",value:counts.customers,icon:UsersRound,href:"/users"},{label:"Produits",value:counts.products,icon:Boxes,href:"/catalog"},{label:"Catégories",value:counts.categories,icon:FolderKanban,href:"/catalog"},{label:"Articles & contenus",value:counts.articles,icon:FileText,href:"/content"},{label:"Commandes",value:counts.orders,icon:ReceiptText,href:"/orders"}];
 return <AdminGuard><AdminShell><Head kicker="PILOTAGE / RÉSUMÉ DU SITE" title="Vue d’ensemble" copy="Les chiffres clés et les actions à traiter, à partir des données actuelles de la boutique."/>{error&&<div className="notice" style={{marginBottom:14}}>{error}</div>}
  <section className="cards overview-cards">{cards.map(({label,value,icon:Icon,href})=><Link key={label} href={href} className="card overview-card"><Icon/><strong>{value}</strong><small>{label}</small></Link>)}</section>
  <section className="card overview-orders"><div className="overview-section-head"><div><p className="eyebrow">À TRAITER</p><h2>État des commandes</h2></div><Link className="btn ghost" href="/orders">Voir les commandes</Link></div><div className="order-status-cards"><div><span>En attente</span><b>{summary.pending}</b></div><div><span>Validées</span><b>{summary.confirmed}</b></div><div><span>Terminées</span><b>{summary.delivered}</b></div><div><span>Annulées</span><b>{summary.cancelled}</b></div></div></section>
  <section className="overview-grid"><div className="card"><div className="overview-section-head"><div><p className="eyebrow">VENTES RÉELLES</p><h2>Revenus</h2></div></div><div className="revenue-totals"><div><small>Commandes confirmées / en cours / livrées</small><b>{fcfa(summary.generated)}</b></div><div><small>Paiements marqués reçus</small><b>{fcfa(summary.paid)}</b></div></div><h3 className="chart-title">Encaissements des 6 derniers mois</h3>{orders.length? <div className="revenue-chart" aria-label="Revenus mensuels encaissés">{summary.buckets.map(bucket=><div key={bucket.key} className="revenue-column"><span>{bucket.amount?fcfa(bucket.amount):"—"}</span><div><i style={{height:`${Math.max(4,(bucket.amount/maxMonth)*100)}%`}}/></div><small>{bucket.label}</small></div>)}</div>:<div className="cms-empty">Aucune commande enregistrée pour le moment.</div>}</div>
  <div className="card"><div className="overview-section-head"><div><p className="eyebrow">RETOURS CLIENTS</p><h2>Avis du site</h2></div><Link className="btn ghost" href="/reviews">Consulter</Link></div>{eligible.length?<><div className="review-score"><Star fill="currentColor"/><b>{average.toFixed(1)} / 5</b><span>{eligible.length} avis</span></div><div className="rating-bars">{[5,4,3,2,1].map(stars=>{const count=eligible.filter(r=>r.rating===stars).length;return <div key={stars}><span>{stars} ★</span><i><b style={{width:`${eligible.length?count/eligible.length*100:0}%`}}/></i><small>{count}</small></div>})}</div><div className="recent-reviews">{eligible.slice(0,3).map(review=><div key={review.id}><span>{"★".repeat(review.rating)}{"☆".repeat(5-review.rating)}</span><p>{review.comment||"Note sans commentaire"}</p><small>{new Date(review.created_at).toLocaleDateString("fr-FR")}</small></div>)}</div></>:<div className="cms-empty"><Star size={28}/><span>Aucun avis reçu pour le moment.</span></div>}</div></section>
  <section className="overview-grid"><div className="card"><div className="overview-section-head"><div><p className="eyebrow">ACTIVITÉ</p><h2>Modifications récentes</h2></div><Link className="btn ghost" href="/system">Voir tout</Link></div>{audit.length?<div className="activity-list">{audit.map(item=>{const label=String(item.details?.label||"").trim();const action=actionNames[item.action]||"a effectué une action sur";const entity=entityNames[item.entity_type]||"un élément";return <article key={item.id}><span className="activity-dot"/><div><p><b>{item.actorName}</b> {action} {entity}{label&&<strong> « {label} »</strong>}</p><small>{new Date(item.created_at).toLocaleString("fr-FR")}</small></div></article>})}</div>:<div className="cms-empty"><Activity size={28}/><span>Aucune modification récente.</span></div>}</div><div className="card"><p className="eyebrow">ACCÈS RAPIDE</p><h2>Que souhaitez-vous faire ?</h2><div className="overview-quick">{[{label:"Ajouter un produit",href:"/catalog",icon:Boxes},{label:"Créer une promotion",href:"/promotions",icon:FileText},{label:"Mettre à jour le site",href:"/website",icon:Activity},{label:"Traiter une commande",href:"/orders",icon:ReceiptText}].map(({label,href,icon:Icon})=><Link className="btn" href={href} key={label}><Icon size={16}/>{label}</Link>)}</div></div></section>
 </AdminShell></AdminGuard>;
}
