"use client";
import { FormEvent, useEffect, useState } from "react";
import { CalendarClock, ImagePlus, Percent, Plus, Save, Trash2 } from "lucide-react";
import { AdminGuard } from "@/components/guard";
import { AdminShell, Head } from "@/components/shell";
import { requireSupabase } from "@/lib/supabase";
import { fcfa } from "@/lib/format";
type Product = { id: string; name: string; price_fcfa: number; active: boolean };
type Promotion = { id: string; name: string; description: string; image_url: string | null; starts_at: string; ends_at: string; active: boolean };
type Assignment = { promotion_id: string; product_id: string; sale_price_fcfa: number };
type PromoForm = { id: string; name: string; description: string; image_url: string; starts_at: string; ends_at: string; percent: string; active: boolean };
const empty: PromoForm = { id: "", name: "", description: "", image_url: "", starts_at: "", ends_at: "", percent: "10", active: true };
const localDate = (value: string) => { const d = new Date(value); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 16); };
export default function PromotionsPage() {
  const [products, setProducts] = useState<Product[]>([]); const [promotions, setPromotions] = useState<Promotion[]>([]); const [assignments, setAssignments] = useState<Assignment[]>([]);
  const [selected, setSelected] = useState<string[]>([]); const [form, setForm] = useState(empty); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { const s = requireSupabase(); const [p, o, a] = await Promise.all([s.from("products").select("id,name,price_fcfa,active").order("name"), s.from("promotions").select("*").order("created_at", { ascending: false }), s.from("promotion_products").select("promotion_id,product_id,sale_price_fcfa")]); setProducts((p.data || []) as Product[]); setPromotions((o.data || []) as Promotion[]); setAssignments((a.data || []) as Assignment[]); if (p.error || o.error || a.error) setMessage("Les promotions n’ont pas pu être chargées. Réessayez."); }
  useEffect(() => { void load(); }, []);
  async function upload(file?: File) { if (!file) return; setBusy(true); const path = `promotions/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "-")}`; const s = requireSupabase(); const { error } = await s.storage.from("product-images").upload(path, file); if (error) setMessage("La bannière n’a pas pu être envoyée. Réessayez."); else setForm(v => ({ ...v, image_url: s.storage.from("product-images").getPublicUrl(path).data.publicUrl })); setBusy(false); }
  async function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setMessage("");
    try {
      if (!selected.length) throw new Error("Choisissez au moins un produit.");
      const percent = Number(form.percent); if (percent <= 0 || percent >= 100) throw new Error("La réduction doit être entre 1 % et 99 %.");
      const payload = { name: form.name.trim(), description: form.description.trim(), image_url: form.image_url || null, starts_at: new Date(form.starts_at).toISOString(), ends_at: new Date(form.ends_at).toISOString(), active: form.active };
      const s = requireSupabase();
      const result = form.id ? await s.from("promotions").update(payload).eq("id", form.id).select("id").single() : await s.from("promotions").insert({ ...payload, created_by: (await s.auth.getUser()).data.user?.id }).select("id").single();
      if (result.error) throw result.error;
      const promoId = result.data.id;
      if (form.id) { const { error } = await s.from("promotion_products").delete().eq("promotion_id", promoId); if (error) throw error; }
      const links = selected.map(productId => { const product = products.find(p => p.id === productId)!; return { promotion_id: promoId, product_id: productId, sale_price_fcfa: Math.max(1, Math.round(product.price_fcfa * (1 - percent / 100))) }; });
      const { error: linkError } = await s.from("promotion_products").insert(links);
      if (linkError) throw linkError;
      setMessage("Promotion enregistrée. Les prix réduits sont appliqués sur le site pendant les dates choisies."); setForm(empty); setSelected([]); await load();
    } catch { setMessage("La promotion n’a pas pu être enregistrée. Vérifiez les dates et les produits sélectionnés."); } finally { setBusy(false); }
  }
  async function edit(promo: Promotion) { const links = assignments.filter(a => a.promotion_id === promo.id); setSelected(links.map(x => x.product_id)); const sample = links[0] && products.find(p => p.id === links[0].product_id); const percent = sample ? Math.round((1 - links[0].sale_price_fcfa / sample.price_fcfa) * 100) : 10; setForm({ ...promo, image_url: promo.image_url || "", starts_at: localDate(promo.starts_at), ends_at: localDate(promo.ends_at), percent: String(percent) }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function toggle(promo: Promotion) { const { error } = await requireSupabase().from("promotions").update({ active: !promo.active }).eq("id", promo.id); setMessage(error ? "Le statut de la promotion n’a pas pu être modifié." : (promo.active ? "Promotion désactivée." : "Promotion activée.")); await load(); }
  async function remove(promo: Promotion) { if (!window.confirm(`Supprimer l’offre « ${promo.name} » et retirer ses prix réduits ?`)) return; const { error } = await requireSupabase().from("promotions").delete().eq("id", promo.id); setMessage(error ? "Cette offre n’a pas pu être supprimée. Réessayez." : "Offre supprimée."); await load(); }
  const price = (product: Product) => Math.max(1, Math.round(product.price_fcfa * (1 - Number(form.percent || 0) / 100)));
  return <AdminGuard><AdminShell><Head kicker="BOUTIQUE / OFFRES" title="Promotions & offres spéciales" copy="Créez une offre datée. Les prix réduits sont vérifiés à nouveau par Supabase au paiement."/>{message && <div className="notice" role="status" style={{ marginBottom: 14 }}>{message}</div>}
    <form className="card" onSubmit={save} style={{ display: "grid", gap: 14, marginBottom: 16 }}><div><p className="eyebrow">{form.id ? "MODIFIER UNE OFFRE" : "NOUVELLE OFFRE"}</p><h2>{form.id ? form.name : "Créer une promotion"}</h2></div><div className="cms-fields"><label>Nom de l’offre<input required value={form.name} onChange={e => setForm(v => ({ ...v, name: e.target.value }))} placeholder="Ex. Offre de rentrée"/></label><label>Réduction (%)<input type="number" required min="1" max="99" value={form.percent} onChange={e => setForm(v => ({ ...v, percent: e.target.value }))}/></label><label>Début<input required type="datetime-local" value={form.starts_at} onChange={e => setForm(v => ({ ...v, starts_at: e.target.value }))}/></label><label>Fin<input required type="datetime-local" value={form.ends_at} onChange={e => setForm(v => ({ ...v, ends_at: e.target.value }))}/></label><label className="cms-wide">Description<textarea rows={2} value={form.description} onChange={e => setForm(v => ({ ...v, description: e.target.value }))}/></label></div>
      <div className="cms-promo-media"><label className="btn"><ImagePlus size={16}/>Ajouter une bannière<input type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e => void upload(e.target.files?.[0])}/></label>{form.image_url && <img src={form.image_url} alt="Aperçu de la promotion"/>}</div>
      <div><div className="cms-section-title"><h3>Produits concernés</h3><span className="sub">{selected.length} sélectionné(s)</span></div><div className="cms-product-pick">{products.filter(p => p.active).map(product => <label key={product.id} className="cms-product-option"><input type="checkbox" checked={selected.includes(product.id)} onChange={e => setSelected(current => e.target.checked ? [...current, product.id] : current.filter(id => id !== product.id))}/><span><b>{product.name}</b><small>{fcfa(product.price_fcfa)} → {fcfa(price(product))}</small></span></label>)}</div></div>
      <div className="cms-inline-options"><label><input type="checkbox" checked={form.active} onChange={e => setForm(v => ({ ...v, active: e.target.checked }))}/> Activer cette offre</label><button className="btn primary" disabled={busy}><Save size={15}/>{form.id ? "Enregistrer les modifications" : "Créer l’offre"}</button>{form.id && <button type="button" className="btn ghost" onClick={() => { setForm(empty); setSelected([]); }}>Annuler</button>}</div>
    </form>
    <div className="card table-wrap"><table className="table"><thead><tr><th>Offre</th><th>Produits</th><th>Période</th><th>État</th><th>Actions</th></tr></thead><tbody>{promotions.map(promo => { const current = promo.active && new Date(promo.starts_at) <= new Date() && new Date(promo.ends_at) > new Date(); const linked = assignments.filter(a => a.promotion_id === promo.id); return <tr key={promo.id}><td><b>{promo.name}</b><div className="sub">{promo.description}</div></td><td>{linked.map(link => products.find(p => p.id === link.product_id)?.name || "Produit supprimé").join(", ")}</td><td><CalendarClock size={14} style={{ display: "inline", marginRight: 5 }}/>{new Date(promo.starts_at).toLocaleDateString("fr-FR")} – {new Date(promo.ends_at).toLocaleDateString("fr-FR")}</td><td><span className={`tag ${current ? "manager" : ""}`}>{current ? "En cours" : promo.active ? "Programmée / expirée" : "Désactivée"}</span></td><td><button className="btn ghost" onClick={() => void edit(promo)}>Modifier</button> <button className="btn ghost" onClick={() => void toggle(promo)}>{promo.active ? "Désactiver" : "Activer"}</button> <button className="btn ghost" onClick={() => void remove(promo)}><Trash2 size={15}/></button></td></tr>; })}</tbody></table>{!promotions.length && <div className="cms-empty"><Percent size={30}/><b>Aucune promotion</b><span>Les offres actives apparaîtront sur le site public.</span></div>}</div>
  </AdminShell></AdminGuard>;
}
