"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Activity, Boxes, FileText, Globe, MessageSquareQuote, Percent, ReceiptText, UsersRound } from "lucide-react";
import { AdminGuard } from "@/components/guard";
import { AdminShell, Head } from "@/components/shell";
import { requireSupabase } from "@/lib/supabase";
type Log={id:number;action:string;entity_type:string;entity_id:string|null;details:Record<string,unknown>;actor_id:string|null;created_at:string;actor:string};
const names:Record<string,string>={CMS_INSERT:"a ajouté",CMS_UPDATE:"a modifié",CMS_DELETE:"a supprimé",ORDER_STATUS_CHANGED:"a mis à jour le statut de",PAYMENT_STATUS_CHANGED:"a mis à jour le paiement de",USER_ROLE_CHANGED:"a modifié les accès de",STAFF_INVITED:"a invité",STAFF_REMOVED:"a retiré"};const entities:Record<string,string>={product:"un produit",category:"une catégorie",section:"une section",article:"un contenu",promotion:"une promotion",review:"un avis",site_setting:"le contenu du site",order:"une commande",profile:"un compte"};
const shortcuts=[{label:"Contenu du site",href:"/website",icon:Globe},{label:"Catalogue",href:"/catalog",icon:Boxes},{label:"Promotions",href:"/promotions",icon:Percent},{label:"Commandes",href:"/orders",icon:ReceiptText},{label:"Avis reçus",href:"/reviews",icon:MessageSquareQuote},{label:"Utilisateurs",href:"/users",icon:UsersRound},{label:"Pages & sections",href:"/content",icon:FileText}];
export default function ActivityPage(){const[logs,setLogs]=useState<Log[]>([]);const[message,setMessage]=useState("");useEffect(()=>{void(async()=>{const s=requireSupabase();const{data,error}=await s.from("audit_logs").select("id,action,entity_type,entity_id,details,actor_id,created_at").order("created_at",{ascending:false}).limit(100);if(error){setMessage("Impossible de charger l’activité pour le moment.");return}const rows=(data||[])as Omit<Log,"actor">[];const ids=Array.from(new Set(rows.map(r=>r.actor_id).filter((id):id is string=>Boolean(id))));const{data:people}=ids.length?await s.from("profiles").select("id,full_name,email").in("id",ids):{data:[]};const users=new Map((people||[]).map(u=>[u.id,u.full_name||u.email||"Administrateur"]));setLogs(rows.map(row=>({...row,actor:row.actor_id?users.get(row.actor_id)||"Administrateur":"Système"})));})()},[]);return <AdminGuard><AdminShell><Head kicker="SUIVI / ACTIVITÉ" title="Activité & réglages" copy="Qui a changé quoi, et quand. Retrouvez les réglages du site et les dernières actions de l’équipe."/>{message&&<div className="notice" style={{marginBottom:14}}>{message}</div>}<section className="card"><p className="eyebrow">GÉRER LE SITE</p><div className="system-shortcuts">{shortcuts.map(({label,href,icon:Icon})=><Link className="btn" href={href} key={href}><Icon size={16}/>{label}</Link>)}</div></section><section className="card" style={{marginTop:14}}><div className="overview-section-head"><div><p className="eyebrow">JOURNAL DU SITE</p><h2>Modifications récentes</h2></div><span className="tag">{logs.length} actions récentes</span></div>{logs.length?<div className="activity-list">{logs.map(log=>{const action=names[log.action]||"a effectué une action sur";const entity=entities[log.entity_type]||"un élément";const label=String(log.details?.label||"");return <article key={log.id}><span className="activity-dot"/><div><p><b>{log.actor}</b> {action} {entity}{label&&<strong> « {label} »</strong>}</p><small>{new Date(log.created_at).toLocaleString("fr-FR")}</small></div></article>})}</div>:<div className="cms-empty"><Activity size={28}/><b>Aucune activité à afficher</b></div>}</section></AdminShell></AdminGuard>}
