"use client";
import { FormEvent, useEffect, useState } from "react";
import { UserPlus, Trash2, UsersRound } from "lucide-react";
import { AdminGuard } from "@/components/guard";
import { AdminShell, Head } from "@/components/shell";
import { requireSupabase } from "@/lib/supabase";
type Profile={id:string;full_name:string|null;phone:string|null;email:string|null;role:"customer"|"store_manager"|"system_admin";active:boolean;created_at:string};
export default function Users(){
 const [items,setItems]=useState<Profile[]>([]),[error,setError]=useState(""),[email,setEmail]=useState(""),[fullName,setFullName]=useState(""),[role,setRole]=useState<"system_admin"|"store_manager">("store_manager"),[busy,setBusy]=useState(false);
 const load=async()=>{const{data,error}=await requireSupabase().from("profiles").select("*").order("created_at",{ascending:false});if(error)setError("Impossible de charger les comptes pour le moment.");setItems((data||[]) as Profile[])};useEffect(()=>{void load()},[]);
 async function update(id:string,nextRole:Profile["role"],active:boolean){setError("");const{error}=await requireSupabase().rpc("admin_set_user_role",{p_user_id:id,p_role:nextRole,p_active:active});if(error)setError("La modification du compte a échoué. Réessayez.");await load()}
 async function invite(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const s=requireSupabase(),{data:{session}}=await s.auth.getSession();const response=await fetch("/api/admin-users",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session?.access_token||""}`},body:JSON.stringify({email,fullName,role})});const result=await response.json() as {error?:string};if(!response.ok)setError("Invitation impossible. Vérifiez l’adresse e-mail et réessayez.");else{setEmail("");setFullName("");setError("Invitation envoyée. La personne recevra un lien pour rejoindre l’équipe.");await load()}setBusy(false)}
 async function remove(person:Profile){if(!window.confirm(`Supprimer le compte d’équipe ${person.email||person.full_name||""} ?`))return;const s=requireSupabase(),{data:{session}}=await s.auth.getSession();const response=await fetch("/api/admin-users",{method:"DELETE",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session?.access_token||""}`},body:JSON.stringify({userId:person.id})});const result=await response.json() as {error?:string};setError(response.ok?"Compte d’équipe supprimé.":"Suppression impossible. Réessayez.");await load()}
 const customerCount=items.filter(person=>person.role==="customer").length; const staffCount=items.filter(person=>person.role!=="customer").length;
 return <AdminGuard><AdminShell><Head kicker="ÉQUIPE" title="Administrateurs & utilisateurs" copy="Consultez les comptes clients et gérez les accès de l’équipe."/>{error&&<div className="error" style={{marginBottom:14}}>{error}</div>}<section className="cards user-counts"><div className="card"><UsersRound/><strong>{customerCount}</strong><small>Clients avec un compte</small></div><div className="card"><UserPlus/><strong>{staffCount}</strong><small>Membres de l’équipe</small></div></section><form className="card" onSubmit={invite} style={{display:"grid",gap:12,marginBottom:16}}><h2><UserPlus size={18} style={{display:"inline",marginRight:8}}/>Inviter un administrateur</h2><p className="sub">La personne recevra un e-mail pour rejoindre l’équipe et créer son accès.</p><div className="cms-fields"><label>Nom complet<input required value={fullName} onChange={e=>setFullName(e.target.value)}/></label><label>E-mail<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Rôle<select value={role} onChange={e=>setRole(e.target.value as typeof role)}><option value="store_manager">Responsable de boutique</option><option value="system_admin">Administrateur principal</option></select></label></div><button className="btn primary" style={{justifySelf:"start"}} disabled={busy}><UserPlus size={15}/>Envoyer invitation</button></form><div className="card table-wrap"><table className="table"><thead><tr><th>Profil</th><th>Rôle</th><th>État</th><th>Créé</th><th>Actions</th></tr></thead><tbody>{items.map(u=><tr key={u.id}><td><b>{u.full_name||"Sans nom"}</b><div className="sub">{u.email||u.phone||"Coordonnées non renseignées"}</div></td><td><select value={u.role} onChange={e=>void update(u.id,e.target.value as Profile["role"],u.active)} className={`tag ${u.role==="system_admin"?"admin":u.role==="store_manager"?"manager":""}`}><option value="customer">Client</option><option value="store_manager">Responsable de boutique</option><option value="system_admin">Administrateur principal</option></select></td><td><button className={`btn ${u.active?"ghost":"primary"}`} onClick={()=>void update(u.id,u.role,!u.active)}>{u.active?"Actif":"Désactivé"}</button></td><td>{new Date(u.created_at).toLocaleDateString("fr-FR")}</td><td>{u.role!=="customer"&&<button className="btn ghost" onClick={()=>void remove(u)} aria-label={`Supprimer ${u.email||u.full_name||"le compte"}`}><Trash2 size={15}/>Retirer</button>}</td></tr>)}</tbody></table>{!items.length&&<p className="sub">Aucun profil visible.</p>}</div></AdminShell></AdminGuard>
}
