"use client";
import { useEffect, useMemo, useState } from "react";
import { MessageSquareQuote, Star } from "lucide-react";
import { AdminGuard } from "@/components/guard";
import { AdminShell, Head } from "@/components/shell";
import { requireSupabase } from "@/lib/supabase";
type Review = { id: string; rating: number; comment: string; status: "pending" | "visible" | "hidden"; created_at: string; user_id: string | null; customer?: string };
export default function ReviewsPage() {
 const [items,setItems]=useState<Review[]>([]);const [filter,setFilter]=useState("all");const [message,setMessage]=useState("");const [busy,setBusy]=useState("");
 async function load(){const s=requireSupabase();const {data,error}=await s.from("site_reviews").select("id,rating,comment,status,created_at,user_id").order("created_at",{ascending:false});if(error){setMessage("Les avis n’ont pas pu être chargés. Réessayez.");return}const rows=(data||[]) as Review[];const ids=Array.from(new Set(rows.map(r=>r.user_id).filter((id):id is string=>Boolean(id))));const people=ids.length?await s.from("profiles").select("id,full_name,email").in("id",ids):{data:[]};const names=new Map((people.data||[]).map(p=>[p.id,p.full_name||p.email||"Client"]));setItems(rows.map(r=>({...r,customer:r.user_id?names.get(r.user_id)||"Client":"Compte supprimé"})));}
 useEffect(()=>{void load()},[]);
 async function setStatus(review:Review,status:Review["status"]){setBusy(review.id);const {error}=await requireSupabase().from("site_reviews").update({status}).eq("id",review.id);setMessage(error?"La visibilité de cet avis n’a pas pu être modifiée.":"Avis mis à jour.");await load();setBusy("");}
 async function remove(review:Review){if(!window.confirm("Supprimer définitivement cet avis ?"))return;setBusy(review.id);const {error}=await requireSupabase().from("site_reviews").delete().eq("id",review.id);setMessage(error?"Cet avis n’a pas pu être supprimé.":"Avis supprimé.");await load();setBusy("");}
 const filtered=useMemo(()=>filter==="all"?items:items.filter(i=>i.status===filter),[items,filter]);const average=items.length?items.reduce((n,r)=>n+r.rating,0)/items.length:0;
 return <AdminGuard><AdminShell><Head kicker="CLIENTS / RETOURS" title="Avis & commentaires" copy="Consultez les retours et choisissez les commentaires visibles sur le site."/>{message&&<div className="notice" role="status" style={{marginBottom:14}}>{message}</div>}<section className="cards"><div className="card"><Star/><strong>{items.length?average.toFixed(1):"—"} / 5</strong><small>note moyenne reçue</small></div><div className="card"><MessageSquareQuote/><strong>{items.length}</strong><small>avis reçus</small></div><div className="card"><MessageSquareQuote/><strong>{items.filter(i=>i.status==="pending").length}</strong><small>à examiner</small></div></section><div className="card table-wrap" style={{marginTop:16}}><div className="overview-section-head"><h2>Retours clients</h2><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Tous les avis</option><option value="pending">À examiner</option><option value="visible">Visibles</option><option value="hidden">Masqués</option></select></div>{filtered.length?<table className="table"><thead><tr><th>Note</th><th>Commentaire</th><th>Client</th><th>Reçu le</th><th>Visibilité</th><th/></tr></thead><tbody>{filtered.map(review=><tr key={review.id}><td><b className="rating-stars">{"★".repeat(review.rating)}{"☆".repeat(5-review.rating)}</b></td><td>{review.comment||<span className="sub">Aucun commentaire</span>}</td><td>{review.customer}</td><td>{new Date(review.created_at).toLocaleString("fr-FR")}</td><td><span className={`tag ${review.status==="visible"?"manager":review.status==="hidden"?"danger":""}`}>{review.status==="pending"?"À examiner":review.status==="visible"?"Publié":"Masqué"}</span></td><td><button className="btn ghost" disabled={busy===review.id} onClick={()=>void setStatus(review,review.status==="visible"?"hidden":"visible")}>{review.status==="visible"?"Masquer":"Publier"}</button> <button className="btn ghost" disabled={busy===review.id} onClick={()=>void remove(review)}>Supprimer</button></td></tr>)}</tbody></table>:<div className="cms-empty"><MessageSquareQuote size={28}/><b>Aucun avis dans cette liste</b></div>}</div></AdminShell></AdminGuard>;
}
