import type { Category, Product } from "@/lib/types";

export const categories: Category[] = [
  {
    id: "chaussettes",
    name: "Chaussettes & chaussons",
    description: "Des petits pas bien au chaud.",
    image: "/products/chaussettes-rose.webp",
    accent: "#9EDAF0",
  },
  {
    id: "vetements",
    name: "Vêtements bébé",
    description: "Des tenues douces pour chaque journée.",
    image: "/products/ensemble-douceur.webp",
    accent: "#FFB8CD",
  },
  {
    id: "sommeil",
    name: "Sommeil & literie",
    description: "Tout pour des nuits paisibles.",
    image: "/products/pyjama-tendre.webp",
    accent: "#B8CBEA",
  },
  {
    id: "eveil",
    name: "Jouets & éveil",
    description: "Des découvertes à portée de main.",
    image: "/products/eveil-doux.webp",
    accent: "#F7C77C",
  },
  {
    id: "repas",
    name: "Repas & alimentation",
    description: "Des repas plus simples, des sourires en plus.",
    image: "/products/coffret-repas.webp",
    accent: "#B4DDD1",
  },
  {
    id: "bain",
    name: "Bain & soin",
    description: "Un cocon de soin au quotidien.",
    image: "/products/kit-bain.webp",
    accent: "#F6D4B8",
  },
  {
    id: "accessoires",
    name: "Accessoires bébé",
    description: "Les essentiels qui suivent la famille.",
    image: "/products/sac-maternite.webp",
    accent: "#C7D2E9",
  },
];

export const products: Product[] = [
  {
    id: "fallback-1",
    variantId: "fallback-1001",
    slug: "ensemble-douceur-rose",
    name: "Ensemble Douceur rose",
    description: "Combinaison, bonnet et gilet en maille souple.",
    categoryId: "vetements",
    price: 18500,
    image: "/products/ensemble-douceur.webp",
    age: "0–6 mois",
    size: "0–3 mois",
    gender: "Fille",
    color: "Rose",
    available: true,
    featured: true,
  },
  {
    id: "fallback-2",
    variantId: "fallback-1002",
    slug: "coffret-premier-repas",
    name: "Coffret Premier repas",
    description: "Set complet à compartiments, pensé pour les petites mains.",
    categoryId: "repas",
    price: 12500,
    image: "/products/coffret-repas.webp",
    age: "6–18 mois",
    size: "Unique",
    gender: "Mixte",
    color: "Ivoire",
    available: true,
    featured: true,
  },
  {
    id: "fallback-3",
    variantId: "fallback-1003",
    slug: "sac-maternite-chicco",
    name: "Sac maternité Week-end",
    description: "Un ensemble spacieux pour garder chaque essentiel organisé.",
    categoryId: "accessoires",
    price: 32000,
    image: "/products/sac-maternite.webp",
    age: "Tous âges",
    size: "Grand",
    gender: "Mixte",
    color: "Gris",
    available: true,
    featured: true,
  },
  {
    id: "fallback-4",
    variantId: "fallback-1004",
    slug: "kit-bain-complet",
    name: "Rituel de bain complet",
    description: "Baignoire ergonomique et accessoires coordonnés.",
    categoryId: "bain",
    price: 38500,
    image: "/products/kit-bain.webp",
    age: "0–18 mois",
    size: "Unique",
    gender: "Mixte",
    color: "Crème",
    available: true,
    featured: true,
  },
  {
    id: "fallback-5",
    variantId: "fallback-1005",
    slug: "chaussettes-noeud-rose",
    name: "Chaussettes Nœud rose",
    description: "Trois paires délicates et confortables.",
    categoryId: "chaussettes",
    price: 5500,
    image: "/products/chaussettes-rose.webp",
    age: "0–12 mois",
    size: "0–6 mois",
    gender: "Fille",
    color: "Rose",
    available: true,
    featured: false,
  },
  {
    id: "fallback-6",
    variantId: "fallback-1006",
    slug: "chaussons-premiers-pas",
    name: "Chaussons Premiers pas",
    description: "Une semelle souple et un maintien léger.",
    categoryId: "chaussettes",
    price: 9500,
    image: "/products/chaussons-bebe.webp",
    age: "6–18 mois",
    size: "18–20",
    gender: "Mixte",
    color: "Bleu",
    available: true,
    featured: false,
  },
  {
    id: "fallback-7",
    variantId: "fallback-1007",
    slug: "ensemble-nuage",
    name: "Ensemble Nuage",
    description: "Un ensemble trois pièces moelleux pour les jours frais.",
    categoryId: "vetements",
    price: 21000,
    image: "/products/ensemble-nuage.webp",
    age: "0–12 mois",
    size: "6–9 mois",
    gender: "Mixte",
    color: "Blanc",
    available: true,
    featured: false,
  },
  {
    id: "fallback-8",
    variantId: "fallback-1008",
    slug: "robette-lapin",
    name: "Robette Petit lapin",
    description: "Robe légère avec bloomer coordonné.",
    categoryId: "vetements",
    price: 14500,
    image: "/products/robette-lapin.webp",
    age: "6–18 mois",
    size: "12 mois",
    gender: "Fille",
    color: "Rose",
    available: true,
    featured: false,
  },
  {
    id: "fallback-9",
    variantId: "fallback-1009",
    slug: "pyjama-nuit-tendre",
    name: "Pyjama Nuit tendre",
    description: "Coton respirant, coupe confortable et finitions douces.",
    categoryId: "sommeil",
    price: 11500,
    image: "/products/pyjama-tendre.webp",
    age: "2–5 ans",
    size: "3 ans",
    gender: "Mixte",
    color: "Bleu",
    available: true,
    featured: false,
  },
  {
    id: "fallback-10",
    variantId: "fallback-1010",
    slug: "cape-de-bain-douillette",
    name: "Cape de bain Douillette",
    description: "Une sortie de bain enveloppante et absorbante.",
    categoryId: "bain",
    price: 8500,
    image: "/products/cape-de-bain.webp",
    age: "0–24 mois",
    size: "Unique",
    gender: "Mixte",
    color: "Pastel",
    available: true,
    featured: false,
  },
  {
    id: "fallback-11",
    variantId: "fallback-1011",
    slug: "valise-naissance",
    name: "Valise Naissance",
    description: "Une valise rigide, compacte et facile à nettoyer.",
    categoryId: "accessoires",
    price: 27500,
    image: "/products/valise-bebe.webp",
    age: "Tous âges",
    size: "Moyen",
    gender: "Mixte",
    color: "Gris",
    available: false,
    featured: false,
  },
  {
    id: "fallback-12",
    variantId: "fallback-1012",
    slug: "gilet-marin",
    name: "Gilet Petit marin",
    description: "Maille mi-saison à rayures bleu ciel.",
    categoryId: "vetements",
    price: 13500,
    image: "/products/gilet-marin.webp",
    age: "12–36 mois",
    size: "24 mois",
    gender: "Garçon",
    color: "Bleu",
    available: true,
    featured: false,
  },
];

export const deliveryAreas = [
  { name: "Centre-ville", window: "Aujourd’hui ou demain", fee: 2000 },
  { name: "Périphérie urbaine", window: "1 à 2 jours", fee: 3500 },
  { name: "Hors agglomération", window: "2 à 4 jours", fee: 6000 },
] as const;

export const formatFcfa = (amount: number) =>
  new Intl.NumberFormat("fr-FR").format(amount).replace(/\u202f/g, " ") + " FCFA";
