"use client";
import { FormEvent, useEffect, useState } from "react";
import { Boxes, CheckCircle2, Plus, Truck } from "lucide-react";
import { RoleGuard } from "@/components/role-guard";
import { PageHead, Shell } from "@/components/shell";
import { requireSupabase } from "@/lib/supabase";
import { fcfa } from "@/lib/format";

type Supplier = { id:string; name:string; contact_name:string|null; phone:string|null; email:string|null; active:boolean };
type Product = { id:string; name:string; sku:string };
type PurchaseItem = { id:string; quantity:number; received_quantity:number; unit_cost_fcfa:number; products:{name:string;sku:string}|null };
type PurchaseOrder = { id:string; reference:string; status:string; expected_date:string|null; suppliers:{name:string}|null; purchase_order_items:PurchaseItem[] };

export default function Suppliers(){
  const[items,setItems]=useState<Supplier[]>([]),[products,setProducts]=useState<Product[]>([]),[orders,setOrders]=useState<PurchaseOrder[]>([]);
  const[openSupplier,setOpenSupplier]=useState(false),[openOrder,setOpenOrder]=useState(false),[error,setError]=useState("");
  const load=async()=>{const s=requireSupabase();const[a,b,c]=await Promise.all([
    s.from("suppliers").select("*").order("name"),
    s.from("products").select("id,name,sku").eq("active",true).order("name"),
    s.from("purchase_orders").select("id,reference,status,expected_date,suppliers(name),purchase_order_items(id,quantity,received_quantity,unit_cost_fcfa,products(name,sku))").order("created_at",{ascending:false})
  ]);setItems((a.data||[])as Supplier[]);setProducts((b.data||[])as Product[]);setOrders((c.data||[]) as unknown as PurchaseOrder[])};
  useEffect(()=>{void load()},[]);
  async function saveSupplier(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=new FormData(e.currentTarget);const{error}=await requireSupabase().from("suppliers").insert({name:String(f.get("name")),contact_name:String(f.get("contact_name")||""),phone:String(f.get("phone")||""),email:String(f.get("email")||"")});if(error){setError(error.message);return}setOpenSupplier(false);await load()}
  async function saveOrder(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=new FormData(e.currentTarget),s=requireSupabase();const reference=`PO-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${crypto.randomUUID().slice(0,6).toUpperCase()}`;const{data:po,error:poError}=await s.from("purchase_orders").insert({reference,supplier_id:String(f.get("supplier_id")),status:"ORDERED",expected_date:String(f.get("expected_date")||"")||null,notes:String(f.get("notes")||"")}).select("id").single();if(poError||!po){setError(poError?.message||"Création impossible");return}const{error:itemError}=await s.from("purchase_order_items").insert({purchase_order_id:po.id,product_id:String(f.get("product_id")),quantity:Number(f.get("quantity")),unit_cost_fcfa:Number(f.get("unit_cost_fcfa"))});if(itemError){setError(itemError.message);return}setOpenOrder(false);await load()}
  async function receive(line:PurchaseItem){const remaining=line.quantity-line.received_quantity;if(remaining<=0)return;const raw=prompt(`Quantité reçue (reste ${remaining})`,String(remaining));if(!raw)return;const q=Number(raw);const{error}=await requireSupabase().rpc("receive_purchase_item",{p_item_id:line.id,p_quantity:q});if(error)setError(error.message);await load()}
  return <RoleGuard><Shell><PageHead eyebrow="Approvisionnement" title="Fournisseurs & achats" description="Fournisseurs, bons d’achat et réceptions de stock migrés depuis le module Supply de la conception." actions={<><button className="secondary" onClick={()=>setOpenSupplier(true)}><Plus size={17}/>Fournisseur</button><button className="primary" onClick={()=>setOpenOrder(true)}><Boxes size={17}/>Bon d’achat</button></>}/>{error&&<p className="error" style={{marginBottom:12}}>{error}</p>}
  <section className="section-grid"><div className="panel"><div className="section-title"><h2>Bons d’achat</h2><Boxes size={18}/></div><div className="list">{orders.map(po=><div key={po.id} className="row" style={{display:"block"}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><h3>{po.reference}</h3><p>{po.suppliers?.name||"Fournisseur"} · {po.expected_date||"date libre"}</p></div><span className="badge">{po.status}</span></div><div style={{display:"grid",gap:6,marginTop:10}}>{po.purchase_order_items.map(line=><div key={line.id} style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,padding:"8px 10px",background:"#fff",borderRadius:12}}><span><b>{line.products?.name}</b> · {line.received_quantity}/{line.quantity} reçu(s) · {fcfa(line.unit_cost_fcfa)}</span><button className="secondary" disabled={line.received_quantity>=line.quantity} onClick={()=>void receive(line)}><CheckCircle2 size={15}/>Réception</button></div>)}</div></div>)}</div></div><div className="panel"><div className="section-title"><h2>Fournisseurs</h2><Truck size={18}/></div><div className="list">{items.map(s=><div className="row" key={s.id}><div><h3>{s.name}</h3><p>{s.contact_name||"Contact non renseigné"} · {s.phone||s.email||"—"}</p></div><span className={`badge ${s.active?"good":""}`}>{s.active?"Actif":"Inactif"}</span></div>)}{!items.length&&<p className="muted">Aucun fournisseur.</p>}</div></div></section>
  {openSupplier&&<div className="modal-backdrop"><section className="panel modal"><h2>Nouveau fournisseur</h2><form onSubmit={saveSupplier} className="form-grid"><label>Nom<input name="name" required/></label><label>Contact<input name="contact_name"/></label><div className="two-col"><label>Téléphone<input name="phone"/></label><label>E-mail<input name="email" type="email"/></label></div><button className="primary">Enregistrer</button><button type="button" className="secondary" onClick={()=>setOpenSupplier(false)}>Annuler</button></form></section></div>}
  {openOrder&&<div className="modal-backdrop"><section className="panel modal"><h2>Nouveau bon d’achat</h2><form onSubmit={saveOrder} className="form-grid"><label>Fournisseur<select name="supplier_id" required>{items.filter(x=>x.active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Article<select name="product_id" required>{products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.sku}</option>)}</select></label><div className="two-col"><label>Quantité<input name="quantity" type="number" min="1" defaultValue="1" required/></label><label>Coût unitaire FCFA<input name="unit_cost_fcfa" type="number" min="0" defaultValue="0" required/></label></div><label>Date attendue<input name="expected_date" type="date"/></label><label>Notes<textarea name="notes"/></label><button className="primary">Créer le bon d’achat</button><button type="button" className="secondary" onClick={()=>setOpenOrder(false)}>Annuler</button></form></section></div>}
  </Shell></RoleGuard>}
